### ISSUE TITLE
Video export

### ISSUE THREAD

**Issue by CactusBack** [PadreZippo/sketchfab-legacy-labs#1]
Hey James, big thank you for uploading the screenshot tool!

Any chance the MP4 video export tool can be uploaded too?

I've started using the GIF exporter at https://klaasnienhuis.github.io/experiments/gif-export/ as a substitute, but while it works somewhat okay, the colors are noticeably worse than MP4.

**Comment by PadreZippo** [comment]
Hey, Klaas has a new version of his version of the Labs, including the Video exporter: https://klaasnienhuis-sketchfab-experiments.vercel.app/
